
########## Setup profile directorires
# Simple fun() to create a directory then
# export the path a var
export_and_mkdir() {
  VAR=$1
  DIR=$2
  export $VAR=$DIR
  mkdir -p $DIR
}

# XDG really helps keep your directory structure clean!
# I use it for almost everything
#
#   https://wiki.archlinux.org/index.php/XDG_Base_Directory_support
#   https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
export_and_mkdir  XDG_CONFIG_HOME "$HOME/.config"
export_and_mkdir  XDG_CACHE_HOME  "$HOME/.cache"
export_and_mkdir  XDG_DATA_HOME   "$HOME/.local/share"
export_and_mkdir  RBENV_ROOT      "$XDG_CACHE_HOME/rbenv"
export_and_mkdir  ZSH_CACHE_HOME  "$XDG_CACHE_HOME/zsh"


jeppesen_home=$ZSH_CACHE_HOME/jeppesen
if [ ! -d $powerlevel9k_home ] ; then
 git clone https://github.com/jeppesen-io/homebrew-zsh.git $jeppesen_home
fi

source  $jeppesen_home/plugins/*.zsh
