# Disable MOTD/last login message
touch ~/.hushlogin

########## Setup profile directorires
# Simple fun() to create a directory then
# export the path a var
export_and_mkdir() {
  VAR=$1
  DIR=$2
  export $VAR=$DIR
  mkdir -p $DIR
}

# XDG really helps keep your directory structure clean!
# I use it for almost everything
#
#   https://wiki.archlinux.org/index.php/XDG_Base_Directory_support
#   https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
export_and_mkdir  XDG_CONFIG_HOME "$HOME/.config"
export_and_mkdir  XDG_CACHE_HOME  "$HOME/.cache"
export_and_mkdir  XDG_DATA_HOME   "$HOME/.local/share"
export_and_mkdir  RBENV_ROOT      "$XDG_CACHE_HOME/rbenv"

## Command history configuration
if [ -z "$HISTFILE" ]; then
    HISTFILE=$HOME/.zsh_history
fi

HISTSIZE=10000
SAVEHIST=10000

setopt append_history
setopt extended_history
setopt hist_expire_dups_first
setopt hist_ignore_dups # ignore duplication command history list
setopt hist_ignore_space
setopt hist_verify
setopt inc_append_history
setopt share_history

# The only theme you need!
# Install directly because I found ZSH plugin managers too slow
export POWERLEVEL9K_MODE='awesome-patched'
export POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
export POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status history time)

powerlevel9k_home=$XDG_CACHE_HOME/powerlevel9k
if [ ! -d $powerlevel9k_home ] ; then
 git clone https://github.com/bhilburn/powerlevel9k.git $powerlevel9k_home
fi
source  $powerlevel9k_home/powerlevel9k.zsh-theme

########## rbenv
eval "$(rbenv init -)"
#echo 2.4.0 > ~/.ruby-version

export CHEF_USER=nelson
export EDITOR=vim
export DEFAULT_USER=nelson

# Update stuff
alias update-brew='brew update -v && brew upgrade -v && brew cleanup && brew cask cleanup && brew prune'
alias update-osx='softwareupdate --install --all --verbose'

# misc
alias n='nvim ~/.local/notes.md'

# Bundle
alias be='bundle exec'

# Vagrant
alias vd='vagrant destroy -f'
alias vu='vagrant up'
alias vp='vagrant provision'
alias vs='vagrant ssh'
alias kb='be rake server:kickberks'

# Vagrant combos!
alias kbvu='kb && vd || true && vu '
alias kbvp='kb && vp'

if [ -e ~/src ] ; then
  if [ -e ~/src/chef ] ; then
    cd ~/src/chef
  else
    cd ~/src
  fi
fi

